### ISSUE TITLE
Activities

### ISSUE THREAD

**Issue by niborus** [niborus/weemo-doc#19]
Hinzufügen der Aktivitäten in Sprachkanälen.

`w#activities [youtube, poker, betrayal, fishing, chess]`

Update vom [12.06.12021](https://discord.com/channels/468520211687931914/468520212128595979/853378291066601473)

**Comment by Inkception** [comment]
Hab das schon mal in die Befehlsübersicht gepackt. Ich lasse die Issue dann noch offen, falls du noch genaueres erklären möchtest.
